version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deploy/dockerfiles/Dockerfile
    environment:
     - MONGOHOST=mongodb
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:8.0.9
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo-data/db:/data/db
      - ./.docker/mongo-data/configdb:/data/configdb
    command: mongod --replSet rs0

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb_data_container:
